#!/bin/bash

#This script helps u to put a logo on pictures using imagemagick command line.

echo "Note:: To be able to use this script you must download image magick first"
echo "Type your logo name/path as written(Ex: Photo.png)"
read -e flogoname 
echo "Enter the postion of the photos"
read -e pos
echo "Choose logo position (1,2,3,4):- "
echo "1-Top Right"
echo "2-Top Left"
echo "3-Bottom Right"
echo "4-Bottom Left"
read -e input2
#Outout is where the results is going to be generated
mkdir Output
#array contains the option for the command imagemagick to p 
e=(NorthEast NorthWest SouthEast SouthWest);



	for h in  $pos*.*
	do
		#getting the each photo's width
		pwidth=$(convert "$h" -print "%w %h\n" /dev/null);
		pwidth=$(echo "$pwidth" | cut -d ' ' -s -f2);
		#getting the file extinsion
		ext='.';
		ext+="$(echo "$flogoname" | rev | cut -d '.' -s -f1 |rev)";
		#the new resulting photo's postion	
		slogoname="Output/$(basename $flogoname $ext).png"
		#make the logo's width and hight 20% of the photo's width 'the logo is squared'
		z=$(echo "$(($pwidth*20/100))");
		float=$z;
		float+="x";
		float+=$z;
		#resizing the logo to fit the photo
		convert -background none "$flogoname" -resize "$float" "$slogoname" ;
		i=$(echo "$h" |rev| cut -d / -s -f 1|rev);
		echo " Processing " $i
		#putting the logo on the photo
		composite -background none -gravity ${e[(($input2-1))]} "$slogoname" "$h" ./Output/"output$i" 
		
	done

echo "You are done ,Thank you."

