#!/bin/bash

#This script helps u to put a logo on pictures using imagemagick command line.

echo "Note:: To be able to use this script you must download image magick first"
echo "Type your logo name as written(Ex: Photo.png)"
read logoname
echo "Choose logo position (1,2,3,4):- "
echo "1-Top Right"
echo "2-Top Left"
echo "3-Bottom Right"
echo "4-Bottom Left"
read input2
mkdir Output

if [ $input2 = 1 ] ;then 
	
	for i in *.JPG *.jpg
	do
		echo " Processing " $i
		composite -gravity NorthEast "$logoname" "$i" ./Output/"output$i" 
		
	done
 
elif [ $input2 = 2 ] ;then
	
	for i in *.JPG *.jpg
	do	
		echo " Processing " $i
		composite -gravity NorthWest "$logoname" "$i" ./Output/"output$i"
		
	done
elif [ $input2 = 3 ] ;then

	for i in *.JPG *.jpg
	do
		echo " Processing " $i
		composite -gravity SouthEast "$logoname" "$i" ./Output/"output$i"
		
	done	
elif [ $input2 = 4 ] ;then 

	for i in *.JPG *.jpg
	do
		echo " Processing " $i
		composite -gravity SouthWest "$logoname" "$i" ./Output/"output$i"
		
	done	
fi

echo "You are done ,Thank you."

